[project]
name = "travel-rl-env"
version = "0.1.0"
description = "Adaptive Travel Planner RL Environment"
authors = [
    {name = "Vyshnavi"}
]
dependencies = [
    "flask",
    "openenv-core>=0.2.0"
]

[project.scripts]
server = "server.app:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
